import streamlit as st
import os
import sys

# Add parent dir to path to allow utils imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.firebase_auth import init_firebase, is_logged_in, logout, get_current_user

# Setup page config
st.set_page_config(
    page_title="AI Career Intelligence System",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Dark mode toggle via CSS injection
def add_dark_mode_toggle():
    if "dark_mode" not in st.session_state:
        st.session_state["dark_mode"] = False
        
    on = st.sidebar.toggle("Dark Mode", value=st.session_state["dark_mode"])
    
    if on != st.session_state["dark_mode"]:
        st.session_state["dark_mode"] = on
        st.rerun()

    if st.session_state["dark_mode"]:
        st.markdown(
            """
            <style>
                .stApp { background-color: #1E1E1E; color: #FFFFFF; }
                h1, h2, h3, h4, p, span { color: #FFFFFF !important; }
                div[data-testid="stMetricValue"] { color: #7F77DD !important; }
            </style>
            """,
            unsafe_allow_html=True
        )

def download_models_if_missing():
    models_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'models')
    os.makedirs(models_dir, exist_ok=True)
    if not os.path.exists(os.path.join(models_dir, 'role_model.pkl')):
        # Usually we would import gdown and download here:
        # st.info("Downloading models for the first time... this may take a moment.")
        # import gdown
        # gdown.download_folder('YOUR_GOOGLE_DRIVE_FOLDER_LINK', output=models_dir, quiet=False)
        # st.success("Models downloaed.")
        pass

def main():
    download_models_if_missing()
    init_firebase()
    
    add_dark_mode_toggle()

    # Sidebar
    st.sidebar.info("Welcome to the AI Career Intelligence System. Start by building your profile.")

    # Main content
    st.title("🎯 AI Career Intelligence System")
    st.subheader("Discover your role. Know your worth. Close your gaps.")
    
    st.markdown("---")
    
    col1, col2, col3 = st.columns(3)
    col1.metric("Developers Analysed", "49,000+")
    col2.metric("Tech Roles Covered", "9")
    col3.metric("Skills Tracked", "26")

    st.markdown("### The 5-Step Flow")
    
    st.markdown("""
    1. **Profile Builder:** Input your skills manually, upload a resume, or connect your GitHub.
    2. **Role Prediction:** Find out what roles match your profile using a Random Forest model.
    3. **Salary Benchmarker:** Estimate your market salary based on ML predictions.
    4. **Skill Gap Analysis:** See exactly what you're missing for your dream role.
    5. **AI Narrative & Roadmap:** Get a 90-day learning roadmap generated by Gemini.
    """)

    st.markdown("---")
    
    if st.button("Start Analysis →", type="primary", use_container_width=True):
        st.switch_page("pages/1_profile_builder.py")

if __name__ == "__main__":
    main()
